
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Direct connection for migrations
    url: "postgres://postgres.ezlecsjuqvcqvmfpigkl:Hana223023!@aws-1-ap-south-1.pooler.supabase.com:5432/postgres",
  },
});
